-- =============================================================================
--  Novo CD: "CD - Commerce"
--  40 times (Série A + Série B, na ordem do mapa) x níveis 1 a 6 = 240 endereços.
--  Importe no phpMyAdmin, no banco ecoman77_deposito.
--  Pode rodar de novo sem duplicar (não recria o CD nem endereços que já existem).
--  Precisa do multi_cd.sql e do ordem_posicoes_sp.sql já importados.
-- =============================================================================

SET NAMES utf8mb4;

INSERT INTO `depositos` (`nome`, `ordem_posicoes`, `ativo`, `created_at`, `updated_at`)
SELECT 'CD - Commerce', 'nivel', 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM `depositos` WHERE `nome` = 'CD - Commerce');

SET @cd = (SELECT `id` FROM `depositos` WHERE `nome` = 'CD - Commerce');

INSERT IGNORE INTO `locations`
  (`deposito_id`, `nome`, `corredor`, `esteira`, `eixo_x`, `eixo_y`, `ativo`, `created_at`, `updated_at`)
VALUES
  (@cd, 'Athletico-PR 1', 'Athletico-PR', '1', 2, 1, 1, NOW(), NOW()),
  (@cd, 'Athletico-PR 2', 'Athletico-PR', '2', 2, 2, 1, NOW(), NOW()),
  (@cd, 'Athletico-PR 3', 'Athletico-PR', '3', 2, 3, 1, NOW(), NOW()),
  (@cd, 'Athletico-PR 4', 'Athletico-PR', '4', 2, 4, 1, NOW(), NOW()),
  (@cd, 'Athletico-PR 5', 'Athletico-PR', '5', 2, 5, 1, NOW(), NOW()),
  (@cd, 'Athletico-PR 6', 'Athletico-PR', '6', 2, 6, 1, NOW(), NOW()),
  (@cd, 'Atlético-MG 1', 'Atlético-MG', '1', 4, 1, 1, NOW(), NOW()),
  (@cd, 'Atlético-MG 2', 'Atlético-MG', '2', 4, 2, 1, NOW(), NOW()),
  (@cd, 'Atlético-MG 3', 'Atlético-MG', '3', 4, 3, 1, NOW(), NOW()),
  (@cd, 'Atlético-MG 4', 'Atlético-MG', '4', 4, 4, 1, NOW(), NOW()),
  (@cd, 'Atlético-MG 5', 'Atlético-MG', '5', 4, 5, 1, NOW(), NOW()),
  (@cd, 'Atlético-MG 6', 'Atlético-MG', '6', 4, 6, 1, NOW(), NOW()),
  (@cd, 'Bahia 1', 'Bahia', '1', 6, 1, 1, NOW(), NOW()),
  (@cd, 'Bahia 2', 'Bahia', '2', 6, 2, 1, NOW(), NOW()),
  (@cd, 'Bahia 3', 'Bahia', '3', 6, 3, 1, NOW(), NOW()),
  (@cd, 'Bahia 4', 'Bahia', '4', 6, 4, 1, NOW(), NOW()),
  (@cd, 'Bahia 5', 'Bahia', '5', 6, 5, 1, NOW(), NOW()),
  (@cd, 'Bahia 6', 'Bahia', '6', 6, 6, 1, NOW(), NOW()),
  (@cd, 'Botafogo 1', 'Botafogo', '1', 8, 1, 1, NOW(), NOW()),
  (@cd, 'Botafogo 2', 'Botafogo', '2', 8, 2, 1, NOW(), NOW()),
  (@cd, 'Botafogo 3', 'Botafogo', '3', 8, 3, 1, NOW(), NOW()),
  (@cd, 'Botafogo 4', 'Botafogo', '4', 8, 4, 1, NOW(), NOW()),
  (@cd, 'Botafogo 5', 'Botafogo', '5', 8, 5, 1, NOW(), NOW()),
  (@cd, 'Botafogo 6', 'Botafogo', '6', 8, 6, 1, NOW(), NOW()),
  (@cd, 'Bragantino 1', 'Bragantino', '1', 10, 1, 1, NOW(), NOW()),
  (@cd, 'Bragantino 2', 'Bragantino', '2', 10, 2, 1, NOW(), NOW()),
  (@cd, 'Bragantino 3', 'Bragantino', '3', 10, 3, 1, NOW(), NOW()),
  (@cd, 'Bragantino 4', 'Bragantino', '4', 10, 4, 1, NOW(), NOW()),
  (@cd, 'Bragantino 5', 'Bragantino', '5', 10, 5, 1, NOW(), NOW()),
  (@cd, 'Bragantino 6', 'Bragantino', '6', 10, 6, 1, NOW(), NOW()),
  (@cd, 'Chapecoense 1', 'Chapecoense', '1', 12, 1, 1, NOW(), NOW()),
  (@cd, 'Chapecoense 2', 'Chapecoense', '2', 12, 2, 1, NOW(), NOW()),
  (@cd, 'Chapecoense 3', 'Chapecoense', '3', 12, 3, 1, NOW(), NOW()),
  (@cd, 'Chapecoense 4', 'Chapecoense', '4', 12, 4, 1, NOW(), NOW()),
  (@cd, 'Chapecoense 5', 'Chapecoense', '5', 12, 5, 1, NOW(), NOW()),
  (@cd, 'Chapecoense 6', 'Chapecoense', '6', 12, 6, 1, NOW(), NOW()),
  (@cd, 'Corinthians 1', 'Corinthians', '1', 14, 1, 1, NOW(), NOW()),
  (@cd, 'Corinthians 2', 'Corinthians', '2', 14, 2, 1, NOW(), NOW()),
  (@cd, 'Corinthians 3', 'Corinthians', '3', 14, 3, 1, NOW(), NOW()),
  (@cd, 'Corinthians 4', 'Corinthians', '4', 14, 4, 1, NOW(), NOW()),
  (@cd, 'Corinthians 5', 'Corinthians', '5', 14, 5, 1, NOW(), NOW()),
  (@cd, 'Corinthians 6', 'Corinthians', '6', 14, 6, 1, NOW(), NOW()),
  (@cd, 'Coritiba 1', 'Coritiba', '1', 16, 1, 1, NOW(), NOW()),
  (@cd, 'Coritiba 2', 'Coritiba', '2', 16, 2, 1, NOW(), NOW()),
  (@cd, 'Coritiba 3', 'Coritiba', '3', 16, 3, 1, NOW(), NOW()),
  (@cd, 'Coritiba 4', 'Coritiba', '4', 16, 4, 1, NOW(), NOW()),
  (@cd, 'Coritiba 5', 'Coritiba', '5', 16, 5, 1, NOW(), NOW()),
  (@cd, 'Coritiba 6', 'Coritiba', '6', 16, 6, 1, NOW(), NOW()),
  (@cd, 'Cruzeiro 1', 'Cruzeiro', '1', 18, 1, 1, NOW(), NOW()),
  (@cd, 'Cruzeiro 2', 'Cruzeiro', '2', 18, 2, 1, NOW(), NOW()),
  (@cd, 'Cruzeiro 3', 'Cruzeiro', '3', 18, 3, 1, NOW(), NOW()),
  (@cd, 'Cruzeiro 4', 'Cruzeiro', '4', 18, 4, 1, NOW(), NOW()),
  (@cd, 'Cruzeiro 5', 'Cruzeiro', '5', 18, 5, 1, NOW(), NOW()),
  (@cd, 'Cruzeiro 6', 'Cruzeiro', '6', 18, 6, 1, NOW(), NOW()),
  (@cd, 'Flamengo 1', 'Flamengo', '1', 20, 1, 1, NOW(), NOW()),
  (@cd, 'Flamengo 2', 'Flamengo', '2', 20, 2, 1, NOW(), NOW()),
  (@cd, 'Flamengo 3', 'Flamengo', '3', 20, 3, 1, NOW(), NOW()),
  (@cd, 'Flamengo 4', 'Flamengo', '4', 20, 4, 1, NOW(), NOW()),
  (@cd, 'Flamengo 5', 'Flamengo', '5', 20, 5, 1, NOW(), NOW()),
  (@cd, 'Flamengo 6', 'Flamengo', '6', 20, 6, 1, NOW(), NOW()),
  (@cd, 'Fluminense 1', 'Fluminense', '1', 22, 1, 1, NOW(), NOW()),
  (@cd, 'Fluminense 2', 'Fluminense', '2', 22, 2, 1, NOW(), NOW()),
  (@cd, 'Fluminense 3', 'Fluminense', '3', 22, 3, 1, NOW(), NOW()),
  (@cd, 'Fluminense 4', 'Fluminense', '4', 22, 4, 1, NOW(), NOW()),
  (@cd, 'Fluminense 5', 'Fluminense', '5', 22, 5, 1, NOW(), NOW()),
  (@cd, 'Fluminense 6', 'Fluminense', '6', 22, 6, 1, NOW(), NOW()),
  (@cd, 'Grêmio 1', 'Grêmio', '1', 24, 1, 1, NOW(), NOW()),
  (@cd, 'Grêmio 2', 'Grêmio', '2', 24, 2, 1, NOW(), NOW()),
  (@cd, 'Grêmio 3', 'Grêmio', '3', 24, 3, 1, NOW(), NOW()),
  (@cd, 'Grêmio 4', 'Grêmio', '4', 24, 4, 1, NOW(), NOW()),
  (@cd, 'Grêmio 5', 'Grêmio', '5', 24, 5, 1, NOW(), NOW()),
  (@cd, 'Grêmio 6', 'Grêmio', '6', 24, 6, 1, NOW(), NOW()),
  (@cd, 'Internacional 1', 'Internacional', '1', 26, 1, 1, NOW(), NOW()),
  (@cd, 'Internacional 2', 'Internacional', '2', 26, 2, 1, NOW(), NOW()),
  (@cd, 'Internacional 3', 'Internacional', '3', 26, 3, 1, NOW(), NOW()),
  (@cd, 'Internacional 4', 'Internacional', '4', 26, 4, 1, NOW(), NOW()),
  (@cd, 'Internacional 5', 'Internacional', '5', 26, 5, 1, NOW(), NOW()),
  (@cd, 'Internacional 6', 'Internacional', '6', 26, 6, 1, NOW(), NOW()),
  (@cd, 'Mirassol 1', 'Mirassol', '1', 28, 1, 1, NOW(), NOW()),
  (@cd, 'Mirassol 2', 'Mirassol', '2', 28, 2, 1, NOW(), NOW()),
  (@cd, 'Mirassol 3', 'Mirassol', '3', 28, 3, 1, NOW(), NOW()),
  (@cd, 'Mirassol 4', 'Mirassol', '4', 28, 4, 1, NOW(), NOW()),
  (@cd, 'Mirassol 5', 'Mirassol', '5', 28, 5, 1, NOW(), NOW()),
  (@cd, 'Mirassol 6', 'Mirassol', '6', 28, 6, 1, NOW(), NOW()),
  (@cd, 'Palmeiras 1', 'Palmeiras', '1', 30, 1, 1, NOW(), NOW()),
  (@cd, 'Palmeiras 2', 'Palmeiras', '2', 30, 2, 1, NOW(), NOW()),
  (@cd, 'Palmeiras 3', 'Palmeiras', '3', 30, 3, 1, NOW(), NOW()),
  (@cd, 'Palmeiras 4', 'Palmeiras', '4', 30, 4, 1, NOW(), NOW()),
  (@cd, 'Palmeiras 5', 'Palmeiras', '5', 30, 5, 1, NOW(), NOW()),
  (@cd, 'Palmeiras 6', 'Palmeiras', '6', 30, 6, 1, NOW(), NOW()),
  (@cd, 'Remo 1', 'Remo', '1', 32, 1, 1, NOW(), NOW()),
  (@cd, 'Remo 2', 'Remo', '2', 32, 2, 1, NOW(), NOW()),
  (@cd, 'Remo 3', 'Remo', '3', 32, 3, 1, NOW(), NOW()),
  (@cd, 'Remo 4', 'Remo', '4', 32, 4, 1, NOW(), NOW()),
  (@cd, 'Remo 5', 'Remo', '5', 32, 5, 1, NOW(), NOW()),
  (@cd, 'Remo 6', 'Remo', '6', 32, 6, 1, NOW(), NOW()),
  (@cd, 'Santos 1', 'Santos', '1', 34, 1, 1, NOW(), NOW()),
  (@cd, 'Santos 2', 'Santos', '2', 34, 2, 1, NOW(), NOW()),
  (@cd, 'Santos 3', 'Santos', '3', 34, 3, 1, NOW(), NOW()),
  (@cd, 'Santos 4', 'Santos', '4', 34, 4, 1, NOW(), NOW()),
  (@cd, 'Santos 5', 'Santos', '5', 34, 5, 1, NOW(), NOW()),
  (@cd, 'Santos 6', 'Santos', '6', 34, 6, 1, NOW(), NOW()),
  (@cd, 'São Paulo 1', 'São Paulo', '1', 36, 1, 1, NOW(), NOW()),
  (@cd, 'São Paulo 2', 'São Paulo', '2', 36, 2, 1, NOW(), NOW()),
  (@cd, 'São Paulo 3', 'São Paulo', '3', 36, 3, 1, NOW(), NOW()),
  (@cd, 'São Paulo 4', 'São Paulo', '4', 36, 4, 1, NOW(), NOW()),
  (@cd, 'São Paulo 5', 'São Paulo', '5', 36, 5, 1, NOW(), NOW()),
  (@cd, 'São Paulo 6', 'São Paulo', '6', 36, 6, 1, NOW(), NOW()),
  (@cd, 'Vasco 1', 'Vasco', '1', 38, 1, 1, NOW(), NOW()),
  (@cd, 'Vasco 2', 'Vasco', '2', 38, 2, 1, NOW(), NOW()),
  (@cd, 'Vasco 3', 'Vasco', '3', 38, 3, 1, NOW(), NOW()),
  (@cd, 'Vasco 4', 'Vasco', '4', 38, 4, 1, NOW(), NOW()),
  (@cd, 'Vasco 5', 'Vasco', '5', 38, 5, 1, NOW(), NOW()),
  (@cd, 'Vasco 6', 'Vasco', '6', 38, 6, 1, NOW(), NOW()),
  (@cd, 'Vitória 1', 'Vitória', '1', 40, 1, 1, NOW(), NOW()),
  (@cd, 'Vitória 2', 'Vitória', '2', 40, 2, 1, NOW(), NOW()),
  (@cd, 'Vitória 3', 'Vitória', '3', 40, 3, 1, NOW(), NOW()),
  (@cd, 'Vitória 4', 'Vitória', '4', 40, 4, 1, NOW(), NOW()),
  (@cd, 'Vitória 5', 'Vitória', '5', 40, 5, 1, NOW(), NOW()),
  (@cd, 'Vitória 6', 'Vitória', '6', 40, 6, 1, NOW(), NOW()),
  (@cd, 'América-MG 1', 'América-MG', '1', 42, 1, 1, NOW(), NOW()),
  (@cd, 'América-MG 2', 'América-MG', '2', 42, 2, 1, NOW(), NOW()),
  (@cd, 'América-MG 3', 'América-MG', '3', 42, 3, 1, NOW(), NOW()),
  (@cd, 'América-MG 4', 'América-MG', '4', 42, 4, 1, NOW(), NOW()),
  (@cd, 'América-MG 5', 'América-MG', '5', 42, 5, 1, NOW(), NOW()),
  (@cd, 'América-MG 6', 'América-MG', '6', 42, 6, 1, NOW(), NOW()),
  (@cd, 'Athletic 1', 'Athletic', '1', 44, 1, 1, NOW(), NOW()),
  (@cd, 'Athletic 2', 'Athletic', '2', 44, 2, 1, NOW(), NOW()),
  (@cd, 'Athletic 3', 'Athletic', '3', 44, 3, 1, NOW(), NOW()),
  (@cd, 'Athletic 4', 'Athletic', '4', 44, 4, 1, NOW(), NOW()),
  (@cd, 'Athletic 5', 'Athletic', '5', 44, 5, 1, NOW(), NOW()),
  (@cd, 'Athletic 6', 'Athletic', '6', 44, 6, 1, NOW(), NOW()),
  (@cd, 'Atlético-GO 1', 'Atlético-GO', '1', 46, 1, 1, NOW(), NOW()),
  (@cd, 'Atlético-GO 2', 'Atlético-GO', '2', 46, 2, 1, NOW(), NOW()),
  (@cd, 'Atlético-GO 3', 'Atlético-GO', '3', 46, 3, 1, NOW(), NOW()),
  (@cd, 'Atlético-GO 4', 'Atlético-GO', '4', 46, 4, 1, NOW(), NOW()),
  (@cd, 'Atlético-GO 5', 'Atlético-GO', '5', 46, 5, 1, NOW(), NOW()),
  (@cd, 'Atlético-GO 6', 'Atlético-GO', '6', 46, 6, 1, NOW(), NOW()),
  (@cd, 'Avaí 1', 'Avaí', '1', 48, 1, 1, NOW(), NOW()),
  (@cd, 'Avaí 2', 'Avaí', '2', 48, 2, 1, NOW(), NOW()),
  (@cd, 'Avaí 3', 'Avaí', '3', 48, 3, 1, NOW(), NOW()),
  (@cd, 'Avaí 4', 'Avaí', '4', 48, 4, 1, NOW(), NOW()),
  (@cd, 'Avaí 5', 'Avaí', '5', 48, 5, 1, NOW(), NOW()),
  (@cd, 'Avaí 6', 'Avaí', '6', 48, 6, 1, NOW(), NOW()),
  (@cd, 'Botafogo-SP 1', 'Botafogo-SP', '1', 50, 1, 1, NOW(), NOW()),
  (@cd, 'Botafogo-SP 2', 'Botafogo-SP', '2', 50, 2, 1, NOW(), NOW()),
  (@cd, 'Botafogo-SP 3', 'Botafogo-SP', '3', 50, 3, 1, NOW(), NOW()),
  (@cd, 'Botafogo-SP 4', 'Botafogo-SP', '4', 50, 4, 1, NOW(), NOW()),
  (@cd, 'Botafogo-SP 5', 'Botafogo-SP', '5', 50, 5, 1, NOW(), NOW()),
  (@cd, 'Botafogo-SP 6', 'Botafogo-SP', '6', 50, 6, 1, NOW(), NOW()),
  (@cd, 'Ceará 1', 'Ceará', '1', 52, 1, 1, NOW(), NOW()),
  (@cd, 'Ceará 2', 'Ceará', '2', 52, 2, 1, NOW(), NOW()),
  (@cd, 'Ceará 3', 'Ceará', '3', 52, 3, 1, NOW(), NOW()),
  (@cd, 'Ceará 4', 'Ceará', '4', 52, 4, 1, NOW(), NOW()),
  (@cd, 'Ceará 5', 'Ceará', '5', 52, 5, 1, NOW(), NOW()),
  (@cd, 'Ceará 6', 'Ceará', '6', 52, 6, 1, NOW(), NOW()),
  (@cd, 'CRB 1', 'CRB', '1', 54, 1, 1, NOW(), NOW()),
  (@cd, 'CRB 2', 'CRB', '2', 54, 2, 1, NOW(), NOW()),
  (@cd, 'CRB 3', 'CRB', '3', 54, 3, 1, NOW(), NOW()),
  (@cd, 'CRB 4', 'CRB', '4', 54, 4, 1, NOW(), NOW()),
  (@cd, 'CRB 5', 'CRB', '5', 54, 5, 1, NOW(), NOW()),
  (@cd, 'CRB 6', 'CRB', '6', 54, 6, 1, NOW(), NOW()),
  (@cd, 'Criciúma 1', 'Criciúma', '1', 56, 1, 1, NOW(), NOW()),
  (@cd, 'Criciúma 2', 'Criciúma', '2', 56, 2, 1, NOW(), NOW()),
  (@cd, 'Criciúma 3', 'Criciúma', '3', 56, 3, 1, NOW(), NOW()),
  (@cd, 'Criciúma 4', 'Criciúma', '4', 56, 4, 1, NOW(), NOW()),
  (@cd, 'Criciúma 5', 'Criciúma', '5', 56, 5, 1, NOW(), NOW()),
  (@cd, 'Criciúma 6', 'Criciúma', '6', 56, 6, 1, NOW(), NOW()),
  (@cd, 'Cuiabá 1', 'Cuiabá', '1', 58, 1, 1, NOW(), NOW()),
  (@cd, 'Cuiabá 2', 'Cuiabá', '2', 58, 2, 1, NOW(), NOW()),
  (@cd, 'Cuiabá 3', 'Cuiabá', '3', 58, 3, 1, NOW(), NOW()),
  (@cd, 'Cuiabá 4', 'Cuiabá', '4', 58, 4, 1, NOW(), NOW()),
  (@cd, 'Cuiabá 5', 'Cuiabá', '5', 58, 5, 1, NOW(), NOW()),
  (@cd, 'Cuiabá 6', 'Cuiabá', '6', 58, 6, 1, NOW(), NOW()),
  (@cd, 'Fortaleza 1', 'Fortaleza', '1', 60, 1, 1, NOW(), NOW()),
  (@cd, 'Fortaleza 2', 'Fortaleza', '2', 60, 2, 1, NOW(), NOW()),
  (@cd, 'Fortaleza 3', 'Fortaleza', '3', 60, 3, 1, NOW(), NOW()),
  (@cd, 'Fortaleza 4', 'Fortaleza', '4', 60, 4, 1, NOW(), NOW()),
  (@cd, 'Fortaleza 5', 'Fortaleza', '5', 60, 5, 1, NOW(), NOW()),
  (@cd, 'Fortaleza 6', 'Fortaleza', '6', 60, 6, 1, NOW(), NOW()),
  (@cd, 'Goiás 1', 'Goiás', '1', 62, 1, 1, NOW(), NOW()),
  (@cd, 'Goiás 2', 'Goiás', '2', 62, 2, 1, NOW(), NOW()),
  (@cd, 'Goiás 3', 'Goiás', '3', 62, 3, 1, NOW(), NOW()),
  (@cd, 'Goiás 4', 'Goiás', '4', 62, 4, 1, NOW(), NOW()),
  (@cd, 'Goiás 5', 'Goiás', '5', 62, 5, 1, NOW(), NOW()),
  (@cd, 'Goiás 6', 'Goiás', '6', 62, 6, 1, NOW(), NOW()),
  (@cd, 'Juventude 1', 'Juventude', '1', 64, 1, 1, NOW(), NOW()),
  (@cd, 'Juventude 2', 'Juventude', '2', 64, 2, 1, NOW(), NOW()),
  (@cd, 'Juventude 3', 'Juventude', '3', 64, 3, 1, NOW(), NOW()),
  (@cd, 'Juventude 4', 'Juventude', '4', 64, 4, 1, NOW(), NOW()),
  (@cd, 'Juventude 5', 'Juventude', '5', 64, 5, 1, NOW(), NOW()),
  (@cd, 'Juventude 6', 'Juventude', '6', 64, 6, 1, NOW(), NOW()),
  (@cd, 'Londrina 1', 'Londrina', '1', 66, 1, 1, NOW(), NOW()),
  (@cd, 'Londrina 2', 'Londrina', '2', 66, 2, 1, NOW(), NOW()),
  (@cd, 'Londrina 3', 'Londrina', '3', 66, 3, 1, NOW(), NOW()),
  (@cd, 'Londrina 4', 'Londrina', '4', 66, 4, 1, NOW(), NOW()),
  (@cd, 'Londrina 5', 'Londrina', '5', 66, 5, 1, NOW(), NOW()),
  (@cd, 'Londrina 6', 'Londrina', '6', 66, 6, 1, NOW(), NOW()),
  (@cd, 'Náutico 1', 'Náutico', '1', 68, 1, 1, NOW(), NOW()),
  (@cd, 'Náutico 2', 'Náutico', '2', 68, 2, 1, NOW(), NOW()),
  (@cd, 'Náutico 3', 'Náutico', '3', 68, 3, 1, NOW(), NOW()),
  (@cd, 'Náutico 4', 'Náutico', '4', 68, 4, 1, NOW(), NOW()),
  (@cd, 'Náutico 5', 'Náutico', '5', 68, 5, 1, NOW(), NOW()),
  (@cd, 'Náutico 6', 'Náutico', '6', 68, 6, 1, NOW(), NOW()),
  (@cd, 'Novorizontino 1', 'Novorizontino', '1', 70, 1, 1, NOW(), NOW()),
  (@cd, 'Novorizontino 2', 'Novorizontino', '2', 70, 2, 1, NOW(), NOW()),
  (@cd, 'Novorizontino 3', 'Novorizontino', '3', 70, 3, 1, NOW(), NOW()),
  (@cd, 'Novorizontino 4', 'Novorizontino', '4', 70, 4, 1, NOW(), NOW()),
  (@cd, 'Novorizontino 5', 'Novorizontino', '5', 70, 5, 1, NOW(), NOW()),
  (@cd, 'Novorizontino 6', 'Novorizontino', '6', 70, 6, 1, NOW(), NOW()),
  (@cd, 'Operário-PR 1', 'Operário-PR', '1', 72, 1, 1, NOW(), NOW()),
  (@cd, 'Operário-PR 2', 'Operário-PR', '2', 72, 2, 1, NOW(), NOW()),
  (@cd, 'Operário-PR 3', 'Operário-PR', '3', 72, 3, 1, NOW(), NOW()),
  (@cd, 'Operário-PR 4', 'Operário-PR', '4', 72, 4, 1, NOW(), NOW()),
  (@cd, 'Operário-PR 5', 'Operário-PR', '5', 72, 5, 1, NOW(), NOW()),
  (@cd, 'Operário-PR 6', 'Operário-PR', '6', 72, 6, 1, NOW(), NOW()),
  (@cd, 'Ponte Preta 1', 'Ponte Preta', '1', 74, 1, 1, NOW(), NOW()),
  (@cd, 'Ponte Preta 2', 'Ponte Preta', '2', 74, 2, 1, NOW(), NOW()),
  (@cd, 'Ponte Preta 3', 'Ponte Preta', '3', 74, 3, 1, NOW(), NOW()),
  (@cd, 'Ponte Preta 4', 'Ponte Preta', '4', 74, 4, 1, NOW(), NOW()),
  (@cd, 'Ponte Preta 5', 'Ponte Preta', '5', 74, 5, 1, NOW(), NOW()),
  (@cd, 'Ponte Preta 6', 'Ponte Preta', '6', 74, 6, 1, NOW(), NOW()),
  (@cd, 'São Bernardo 1', 'São Bernardo', '1', 76, 1, 1, NOW(), NOW()),
  (@cd, 'São Bernardo 2', 'São Bernardo', '2', 76, 2, 1, NOW(), NOW()),
  (@cd, 'São Bernardo 3', 'São Bernardo', '3', 76, 3, 1, NOW(), NOW()),
  (@cd, 'São Bernardo 4', 'São Bernardo', '4', 76, 4, 1, NOW(), NOW()),
  (@cd, 'São Bernardo 5', 'São Bernardo', '5', 76, 5, 1, NOW(), NOW()),
  (@cd, 'São Bernardo 6', 'São Bernardo', '6', 76, 6, 1, NOW(), NOW()),
  (@cd, 'Sport 1', 'Sport', '1', 78, 1, 1, NOW(), NOW()),
  (@cd, 'Sport 2', 'Sport', '2', 78, 2, 1, NOW(), NOW()),
  (@cd, 'Sport 3', 'Sport', '3', 78, 3, 1, NOW(), NOW()),
  (@cd, 'Sport 4', 'Sport', '4', 78, 4, 1, NOW(), NOW()),
  (@cd, 'Sport 5', 'Sport', '5', 78, 5, 1, NOW(), NOW()),
  (@cd, 'Sport 6', 'Sport', '6', 78, 6, 1, NOW(), NOW()),
  (@cd, 'Vila Nova 1', 'Vila Nova', '1', 80, 1, 1, NOW(), NOW()),
  (@cd, 'Vila Nova 2', 'Vila Nova', '2', 80, 2, 1, NOW(), NOW()),
  (@cd, 'Vila Nova 3', 'Vila Nova', '3', 80, 3, 1, NOW(), NOW()),
  (@cd, 'Vila Nova 4', 'Vila Nova', '4', 80, 4, 1, NOW(), NOW()),
  (@cd, 'Vila Nova 5', 'Vila Nova', '5', 80, 5, 1, NOW(), NOW()),
  (@cd, 'Vila Nova 6', 'Vila Nova', '6', 80, 6, 1, NOW(), NOW());

-- Conferência: deve mostrar 240 endereços
SELECT d.`id` AS cd_id, d.`nome` AS cd, COUNT(l.`id`) AS enderecos
FROM `depositos` d
LEFT JOIN `locations` l ON l.`deposito_id` = d.`id` AND l.`deleted_at` IS NULL
WHERE d.`nome` = 'CD - Commerce'
GROUP BY d.`id`, d.`nome`;
